### ISSUE TITLE
zzykxx - Reservoir "bid-ask midpoint" oracle can be used instead of the "floor" oracle

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-looksrare-judging#82]
zzykxx

medium

# Reservoir "bid-ask midpoint" oracle can be used instead of the "floor" oracle

## Summary
Users can use the reservoir `Collection bid-ask midpoint` instead of the `Collection floor` pricing.

## Vulnerability Detail
Reservoir NFT oracle offers three main different pricing:
- Collection floor
- Collection bid-ask midpoint
- Collection top bid oracle

The price returned by the oracle determines the amount of entries a user should get when depositing an NFT, the protocol is meant to use the `Collection floor` but a user might decide to use the `Collection bid-ask midpoint` instead because they both return the same [`messageHash`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1613-L1626).

Let's take as an example the pudge penguins collection. 

Querying reservoir for the [`Collection floor`](https://docs.reservoir.tools/reference/getoraclecollectionsflooraskv6):
```bash
curl --request GET \
     --url 'https://api.reservoir.tools/oracle/collections/floor-ask/v6?kind=twap&twapSeconds=3600&collection=0xbd3531da5cf5857e7cfaa92426877b022e612cf8' \
     --header 'accept: */*' \
     --header 'x-api-key: demo-api-key'
```

returns:
```bash
{
  "price": 18.18581,
  "message": {
    "id": "0x15530ce04dad67f6b6e8213c7e5552bc046bb3c404fe4b338dca757a684c684c",
    "payload": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fc60fb68a730bb8e",
    "timestamp": 1706006459,
    "chainId": "1",
    "signature": "0x27d3c605f06b0627263971f73f687a49a9b395de26975c2643c3eb0236af8096523a22911f327c100ca3578cf7ae599c5c0c711dca043718f549ea1dc51f69ed1c"
   }
}
```

Querying reservoir for the [`Collection bid-ask midpoint`](https://docs.reservoir.tools/reference/getoraclecollectionsbidaskmidpointv1):
```bash
curl --request GET \
     --url 'https://api.reservoir.tools/oracle/collections/bid-ask-midpoint/v1?kind=twap&twapSeconds=3600&collection=0xbd3531da5cf5857e7cfaa92426877b022e612cf8' \
     --header 'accept: */*' \
     --header 'x-api-key: demo-api-key'
```
returns:
```bash
{
  "price": 18.0121,
  "message": {
    "id": "0x15530ce04dad67f6b6e8213c7e5552bc046bb3c404fe4b338dca757a684c684c",
    "payload": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f9f7d4c8fff5f31d",
    "timestamp": 1706006939,
    "chainId": "1",
    "signature": "0x7adee5fad3928460773af76aaaa1a969fb1d196de8c879353d21b36d6f30fb091fd177a0b398ee7ed05af8c79e7c702231b4f1cc7f72d38fb17e37b50d96d4f41b"
  }
}
```

As shown the `message.id` is the same, but the price is different. Because the `message.id` is the same it's possible for an user to choose which pricing to use at its discretion.

Since the `Collection bid-ask midpoint` price is always lower than the `Collection floor` this can be used by an attacker to lower the amount of entries a depositor will get and increase his chances of winning as a consequence. 

Let's suppose Alice is participating in round where `valuePerEntry = 0.1ETH` and she already owns 500 entry tickets because of some ETH she deposited.

Bob also wants to join and sends a [`deposit()`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L305) transaction to deposit 10 pudgy penguins. He gets the reservoir oracle signature for the pudgy penguins `Collection floor` for a price of `18.18581ETH` per NFT and submit his transaction. Bob is expecting `18.18/0.1 = 181*10 = 1810` entry tickets. 

Alice notices this and frontruns Bob deposit by depositing a pudgy penguin herself, but she uses the reservoir pricing for the `Collection bid-ask midpoint` instead, this sets the price of a pudgy penguin to `18.0121ETH` for the whole round. Alice receives `18.01/0.1 = 180` entry tickets for this.

At this point Bob transaction goes through, but he receives `18.01/0.1 = 180*10 = 1800` entry tickets instead of `1810`. 

The odds of winning are:
- Alice: (500 + 180)/(500+180+1800) = `27.41%`
- Bob: (1800)/(500+180+1800) = `72.58%`

If Alice deposited a pudgy penguin at the price intended by the protocol instead of the lowered one the odds of winning would have been:
- Alice: (500+181)/(500+180+1810) = `27.34%`
- Bob: (1810)/(500+180+1810) = `72.69%`

## Impact
An attacker is able to increase his chances of winning by lowering the entry tickets received by other participants.

## Code Snippet
 - [`messageHash`](https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1613-L1626)
## Tool used

Manual Review

## Recommendation

I'm not sure why Reservoir allows this to happen. Given that the protocol admins are trusted a fix to this could be to add an extra signature from a protocol-controlled private key on top of the reservoir oracle signature to ensure only the `Collection floor` can be used.

**Comment by 0xhiroshi** [comment]
Reservoir has updated its bid-ask midpoint API and the 2 endpoints no longer return the same message ID

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  valid: price can be manipulated; medium(11)

**Comment by nevillehuang** [comment]
@0xhiroshi does that mean this was fixed before the contest period?

**Comment by 0xhiroshi** [comment]
@nevillehuang We presented this issue to Reservoir and then they fixed it.

**Comment by nevillehuang** [comment]
Before any watsons consider a escalation, I believe this issue is valid because of in-scope code logic actually indicating an issue with retrieving reservoir price due to the use of same messageHash. This issue has in fact gone beyond just the value of a looks-rare audit and required a fix directly on reservoir's API, so I believe it should remain valid, and sherlock should reconsider scoping rules.

Also issue #126, also brought up a possible direct fix within the contract.

**Comment by detectiveking123** [comment]
Escalate

Out of scope

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Out of scope

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by zzykxx** [comment]
Escalate 

I believe this to be in-scope, valid, and high severity as well. The high severity claim comes mainly from the other submitter of this issue "HSB" which contacted me in private with a valid point on why he/she submitted this as high severity.

**Why is it in-scope?**
From the point of view of the smart contract it's possible to submit a valid signature that should not be possible to submit. It shouldn't matter how an attacker acquired the valid signature in the first place as long as I can prove an attacker can acquire it without any pre-condition, which I did. In addition to this, we both highlighted two potential fixes within the looksrare system. The fact that the issue was fixed by reservoir instead shouldn't be used to claim this as out of scope, if anything it highlights the importance of this disclosure which provided value to looksrare, reservoir and any other protocol using reservoir.

**Why is it valid?**
It can cause losses to other participants and the protocol: 
- The entries of a participant can be lowered which implies lower chances of winning (ie. loss of funds)
- The protocol will collect less fees because the total value of the pot is lower than it should

**Why should it be high?**
The difference between the "bid-ask midpoint" and "floor" pricing can be massive. Let's take as example the  [Wrapped Cryptopunks](https://explorer.reservoir.tools/ethereum/collection/0xb7f7f6c52f2e2fdb1963eab30438024864c313f6) collection where the "floor price" is `70ETH` and the "top bid" is `50.09ETH`. The "bid-ask midpoint" will return `60.04ETH`:

```solidity
curl --request GET \
     --url 'https://api.reservoir.tools/oracle/collections/bid-ask-midpoint/v1?kind=twap&twapSeconds=3600&collection=0xb7F7F6C52F2e2fdb1963Eab30438024864c313F6' \
     --header 'accept: */*' \
     --header 'x-api-key: demo-api-key'
```

```bash
{ "price": 60.04, "message": { "id": "0x570d625493d436adc229d29ca37188a46bb310307e934c57bae4410831891618", "payload": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034138ede4fa740000", "timestamp": 1706733347, "chainId": "1", "signature": "0x20e05fbb7f0d983f1a0e4c1f34f242ceffac69d9142a2ff597315705b96873330543463ea7ae519120cf3475bc4d925a5debdf1970ff139cf3301f4603dc40cf1c" } }
```

The difference between the two is about `10ETH`, and can be far more than that if the top bid is lower, which is possible. `10ETH` is about `20000$`, which is a big enough loss to argue for this finding to be classified as high severity given the lack of pre-conditions necessary to execute the attack.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> I believe this to be in-scope, valid, and high severity as well. The high severity claim comes mainly from the other submitter of this issue "HSB" which contacted me in private with a valid point on why he/she submitted this as high severity.
> 
> **Why is it in-scope?**
> From the point of view of the smart contract it's possible to submit a valid signature that should not be possible to submit. It shouldn't matter how an attacker acquired the valid signature in the first place as long as I can prove an attacker can acquire it without any pre-condition, which I did. In addition to this, we both highlighted two potential fixes within the looksrare system. The fact that the issue was fixed by reservoir instead shouldn't be used to claim this as out of scope, if anything it highlights the importance of this disclosure which provided value to looksrare, reservoir and any other protocol using reservoir.
> 
> **Why is it valid?**
> It can cause losses to other participants and the protocol: 
> - The entries of a participant can be lowered which implies lower chances of winning (ie. loss of funds)
> - The protocol will collect less fees because the total value of the pot is lower than it should
> 
> **Why should it be high?**
> The difference between the "bid-ask midpoint" and "floor" pricing can be massive. Let's take as example the  [Wrapped Cryptopunks](https://explorer.reservoir.tools/ethereum/collection/0xb7f7f6c52f2e2fdb1963eab30438024864c313f6) collection where the "floor price" is `70ETH` and the "top bid" is `50.09ETH`. The "bid-ask midpoint" will return `60.04ETH`:
> 
> ```solidity
> curl --request GET \
>      --url 'https://api.reservoir.tools/oracle/collections/bid-ask-midpoint/v1?kind=twap&twapSeconds=3600&collection=0xb7F7F6C52F2e2fdb1963Eab30438024864c313F6' \
>      --header 'accept: */*' \
>      --header 'x-api-key: demo-api-key'
> ```
> 
> ```bash
> { "price": 60.04, "message": { "id": "0x570d625493d436adc229d29ca37188a46bb310307e934c57bae4410831891618", "payload": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034138ede4fa740000", "timestamp": 1706733347, "chainId": "1", "signature": "0x20e05fbb7f0d983f1a0e4c1f34f242ceffac69d9142a2ff597315705b96873330543463ea7ae519120cf3475bc4d925a5debdf1970ff139cf3301f4603dc40cf1c" } }
> ```
> 
> The difference between the two is about `10ETH`, and can be far more than that if the top bid is lower, which is possible. `10ETH` is about `20000$`, which is a big enough loss to argue for this finding to be classified as high severity given the lack of pre-conditions necessary to execute the attack.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by spacegliderrrr** [comment]
Escalate

Issue should remain as is. The case which @zzykxx has showcased requires too many external factors:
1. Victim's NFT collection to have a significant difference in floor-price and bid-ask midpoint.
2. Attacker must own an NFT from that same collection and deposit it (via front-running) into the round in order to set the price (hence, they're also taking a negative expected value bet there)
3. Attacker must have and deposit even more funds in order to cover for their initial negative EV bet and attempt to get an edge. 
4. If all of the above are met, attack will only be profitable if the victim's NFT is a significant part of the pot. e.g. if there are multiple other people and victim's NFT is a small % of the pot, attack remains unprofitable. The attacker takes a risk as if more people join the pot after the attack, attacker will have negative expected value. 

Medium severity is appropriate.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Issue should remain as is. The case which @zzykxx has showcased requires too many external factors:
> 1. Victim's NFT collection to have a significant difference in floor-price and bid-ask midpoint.
> 2. Attacker must own an NFT from that same collection and deposit it (via front-running) into the round in order to set the price (hence, they're also taking a negative expected value bet there)
> 3. Attacker must have and deposit even more funds in order to cover for their initial negative EV bet and attempt to get an edge. 
> 4. If all of the above are met, attack will only be profitable if the victim's NFT is a significant part of the pot. e.g. if there are multiple other people and victim's NFT is a small % of the pot, attack remains unprofitable. The attacker takes a risk as if more people join the pot after the attack, attacker will have negative expected value. 
> 
> Medium severity is appropriate.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xhsp** [comment]
> Escalate
> 
> Issue should remain as is. The case which @zzykxx has showcased requires too many external factors:
> 
> 1. Victim's NFT collection to have a significant difference in floor-price and bid-ask midpoint.
> 2. Attacker must own an NFT from that same collection and deposit it (via front-running) into the round in order to set the price (hence, they're also taking a negative expected value bet there)
> 3. Attacker must have and deposit even more funds in order to cover for their initial negative EV bet and attempt to get an edge.
> 4. If all of the above are met, attack will only be profitable if the victim's NFT is a significant part of the pot. e.g. if there are multiple other people and victim's NFT is a small % of the pot, attack remains unprofitable. The attacker takes a risk as if more people join the pot after the attack, attacker will have negative expected value.
> 
> Medium severity is appropriate.


This is a critical issue.

1. bid-ask midpoint can be easily manipulated by placing a bid price, to verify, feel free to make an collection offer to, for example, [Quirkies Originals](https://explorer.reservoir.tools/ethereum/collection/0x3903d4ffaaa700b62578a66e7a67ba4cb67787f9) and see how bid-ask midpoint changes;
<img width="324" alt="offer" src="https://github.com/sherlock-audit/2024-01-looksrare-judging/assets/155340699/9570ca26-17d2-4fa4-8502-ef0f734f50ce">

2. Attacker don't have to own the NFT, all he need to do is to front-run the first NFT depositor to make an collection offer much lower than the floor price;

3. Because the victim gets a bad price, attacker needs less funds to win the round;

4. Attacker may not be able to win every rounds, because price can be manipulated easily, the attacker will eventually win (many times) by cheating and honest users will suffer a loss.

It's unconfirmed but similarly, attacker can make the price much higher than floor price by placing a high bid price, then attacker can win almost every round.

**Comment by ArnieSec** [comment]
Escalate

The issue is out of scope.

first the returning of the same message id is a bug of reservoir not looks. This is confirmed by the reservoir team as they quickly employed a fix. Because the issue is caused by reservoir, if we look at the readme it should be invalid because of the following snippet from the read me

> NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection.

Floor price provided by reservoir are trusted. This should be sufficient enough argument to disqualify this issue. 

@nevillehuang Suggests that sherlock make an exception in regards to the scoping  
> This issue has in fact gone beyond just the value of a looks-rare audit and required a fix directly on reservoir's API, so I believe it should remain valid, and sherlock should reconsider scoping rules.

In accordance to sherlock documentation this is impossible and prohibited because of the following snippet from sherlocks documentation.
> If rules are updated, the new rules apply only to contests that start after the date of change

Therefore if sherlock were to introduce new scoping rules, they would only apply to contests which start after the date of the new rule implementation.

In conclusion, if the bug was solely a problem of looks code, it would only require a fix to the looks contract. Given that this bug required a fix to an out of scope protocol further shows how this issue is truly out of scope. No exception should be made for this issue because that would be against the rules of sherlock.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The issue is out of scope.
> 
> first the returning of the same message id is a bug of reservoir not looks. This is confirmed by the reservoir team as they quickly employed a fix. Because the issue is caused by reservoir, if we look at the readme it should be invalid because of the following snippet from the read me
> 
> > NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection.
> 
> Floor price provided by reservoir are trusted. This should be sufficient enough argument to disqualify this issue. 
> 
> @nevillehuang Suggests that sherlock make an exception in regards to the scoping  
> > This issue has in fact gone beyond just the value of a looks-rare audit and required a fix directly on reservoir's API, so I believe it should remain valid, and sherlock should reconsider scoping rules.
> 
> In accordance to sherlock documentation this is impossible and prohibited because of the following snippet from sherlocks documentation.
> > If rules are updated, the new rules apply only to contests that start after the date of change
> 
> Therefore if sherlock were to introduce new scoping rules, they would only apply to contests which start after the date of the new rule implementation.
> 
> In conclusion, if the bug was solely a problem of looks code, it would only require a fix to the looks contract. Given that this bug required a fix to an out of scope protocol further shows how this issue is truly out of scope. No exception should be made for this issue because that would be against the rules of sherlock.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xhsp** [comment]
The issue is in scope.

Even if the fix is employed by Reservoir does not mean it's entirely Reservoir's fault.

If we compare the **Collection bid-ask midpoint API** and **Collection floor API** provided by Reservoir we can find there are same parameters accepted by both APIs:
> Collection bid-ask midpoint
<img width="714" alt="Collection bid-ask midpoint" src="https://github.com/sherlock-audit/2024-01-looksrare-judging/assets/155340699/abe2ed35-1015-4e59-a819-d00a9a4d1ba7">

> Collection floor
<img width="714" alt="Collection floor" src="https://github.com/sherlock-audit/2024-01-looksrare-judging/assets/155340699/fd18813b-fc49-44d7-b525-89c8200dab8b">

But there are additional parameters accepted by Collection floor API only: **eip3668Calldata** and **useNonFlaggedFloorAsk**

It's fine for regular users to call these 2 different APIs with the same parameters, however, protocol like Looksrare should be extremely careful when using the API, **the culprit is Reservoir Oracle is not properly used by the protocol**.

> In conclusion, if the bug was solely a problem of looks code, it would only require a fix to the looks contract

In fact, there is no need for Reservoir to do the fix, The recommendations given by me and the other watson are both feasible, a fix to the looks contract itself is all it needs.

> NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection.

NFT floor prices are trusted doesn't mean the protocol would accept bid-ask midpoint price as floor price. 

Last but not least, as I demonstrated in my earlier comment, this issue is critical, invalidating it would only discourage watsons to bring up such vulnerabilities and there is no good to the community.

**Comment by nevillehuang** [comment]
I agree with @zzykxx and @0xhsp, if sherlock and watsons as auditors fails to see the value of this issue, it is beyond me honestly, I would simply have to respect enforcement of sherlock rules by @Czar102. I think given the fix can be done both via contracts and external API, I see why watsons could be debating both ways. I apologize if this is abit of an personal opinion, but you can't deny there are certain facts in it as well. Additionally, given the possible large price descrepencies, if valid, I support it raising in severity given the unfairness of game mechanism it can bring allowing users depositing way higher than intended number of entries per deposit.

**Comment by 0xhiroshi** [comment]
> The issue is in scope.
> 
> Even if the fix is employed by Reservoir does not mean it's entirely Reservoir's fault.
> 
> If we compare the **Collection bid-ask midpoint API** and **Collection floor API** provided by Reservoir we can find there are same parameters accepted by both APIs:
> 
> > Collection bid-ask midpoint
> 
> <img alt="Collection bid-ask midpoint" width="714" src="https://private-user-images.githubusercontent.com/155340699/301744361-abe2ed35-1015-4e59-a819-d00a9a4d1ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjA0NjQsIm5iZiI6MTcwNjg2MDE2NCwicGF0aCI6Ii8xNTUzNDA2OTkvMzAxNzQ0MzYxLWFiZTJlZDM1LTEwMTUtNGU1OS1hODE5LWQwMGE5YTRkMWJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNzQ5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDg3NTJiZDg4ZDg5NTcwNDMyMmFjMjJhOTRlYmI0Zjk3MDY0M2Y1N2FmNzA0MWEwNjNlYjE5NDQyOWRjNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AVH3t11Goopb8uIQ0JDhkw4rVdilHnJMZ-L-UyiiIas">
> > Collection floor
> 
> <img alt="Collection floor" width="714" src="https://private-user-images.githubusercontent.com/155340699/301744481-fd18813b-fc49-44d7-b525-89c8200dab8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjA0NjQsIm5iZiI6MTcwNjg2MDE2NCwicGF0aCI6Ii8xNTUzNDA2OTkvMzAxNzQ0NDgxLWZkMTg4MTNiLWZjNDktNDRkNy1iNTI1LTg5YzgyMDBkYWI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNzQ5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmEwN2Q0ZGViNmE2NjVhNTkwYWVjMjMwZjA3ODY1YTBkNmVlMDYzNzJmNWUxNGYyODdjOTJiNWRjNDE2MDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HxCEiTbvctO0hGSpLJDiPe4G9VrMzvvCSwwCMZmKJd0">
> But there are additional parameters accepted by Collection floor API only: **eip3668Calldata** and **useNonFlaggedFloorAsk**
> 
> It's fine for regular users to call these 2 different APIs with the same parameters, however, protocol like Looksrare should be extremely careful when using the API, **the culprit is Reservoir Oracle is not properly used by the protocol**.
> 
> > In conclusion, if the bug was solely a problem of looks code, it would only require a fix to the looks contract
> 
> In fact, there is no need for Reservoir to do the fix, The recommendations given by me and the other watson are both feasible, a fix to the looks contract itself is all it needs.
> 
> > NFT floor prices provided by Reservoir are expected to be trusted and will be used to value any token id in the same collection.
> 
> NFT floor prices are trusted doesn't mean the protocol would accept bid-ask midpoint price as floor price.
> 
> Last but not least, as I demonstrated in my earlier comment, this issue is critical, invalidating it would only discourage watsons to bring up such vulnerabilities and there is no good to the community.

https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L96
https://github.com/sherlock-audit/2024-01-looksrare/blob/main/contracts-yolo/contracts/YoloV2.sol#L1606

We do check `onlyNonFlaggedTokens` in the contract though

**Comment by Czar102** [comment]
I can see the immense value of these reports, nevertheless they are concerning off-chain behavior of an infrastructure provider, and they are out of scope of this audit. It would be unfair to reward it with respect to other Watsons who trusted the infrastructure provider according to Sherlock's rules.

I believe it doesn't have to be the end of the story of this issue, though. I may follow up on it later on.

I'm planning to invalidate the issue and duplicates.

**Comment by detectiveking123** [comment]
@nevillehuang We do see the value of this report. It is just invalid according to Sherlock rules. There are many low / informational values that are useful to the protocol team.

**Comment by nevillehuang** [comment]
@detectiveking123 The impact of this is definitely not low/informational. But I get it, and respect any decision made by head of judging.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [detectiveking123](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/82/#issuecomment-1920819347): accepted
- [ArnieGod](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/82/#issuecomment-1922354398): accepted
- [zzykxx](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/82/#issuecomment-1921081018): rejected
- [spacegliderrrr](https://github.com/sherlock-audit/2024-01-looksrare-judging/issues/82/#issuecomment-1921285643): rejected
